version: '3'

services:
  bot:
    build:
      context: .
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:+admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:+password}
    volumes:
      - ./data:/data/db
    command: mongod --bind_ip_all