version: '3'

services:
  bot:
    build:
      context: .
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
      - ./data:/data/db
    command: mongod --bind_ip_all